<?php
/*
 * JSONElement.php
 * Initial Commit: Paul Anderson, 1/24/2018
 * iResource implementation holding data for JSON objects generated by APIView objects.
 * 
 */

include_once LIBPATH.'php/toonces.php';

class JSONElement implements iResource
{
    var $JSONObjects = array();
    var $elementsCount = 0;
    
    
    public function addElement ($element) {
        
        array_push($this->JSONObjects,$element);
        $this->elementsCount++;
        
    }
    
    // execution method
    public function getResource() {
        
        $JSONString = json_encode($this->JSONObjects, JSON_PRETTY_PRINT);
        return $JSONString;
        
    }
}